typedef enum {
    OX_KEYWORD_NONE  = -1,
    OX_KEYWORD_BEGIN = 512,
    OX_KEYWORD_null,
    OX_KEYWORD_true,
    OX_KEYWORD_false,
    OX_KEYWORD_func,
    OX_KEYWORD_class,
    OX_KEYWORD_static,
    OX_KEYWORD_enum,
    OX_KEYWORD_bitfield,
    OX_KEYWORD_if,
    OX_KEYWORD_elif,
    OX_KEYWORD_else,
    OX_KEYWORD_while,
    OX_KEYWORD_do,
    OX_KEYWORD_for,
    OX_KEYWORD_as,
    OX_KEYWORD_case,
    OX_KEYWORD_break,
    OX_KEYWORD_continue,
    OX_KEYWORD_return,
    OX_KEYWORD_try,
    OX_KEYWORD_catch,
    OX_KEYWORD_finally,
    OX_KEYWORD_throw,
    OX_KEYWORD_typeof,
    OX_KEYWORD_instof,
    OX_KEYWORD_ref,
    OX_KEYWORD_public,
    OX_KEYWORD_this,
    OX_KEYWORD_argv,
    OX_KEYWORD_sched,
    OX_KEYWORD_yield,
    OX_KEYWORD_global,
    OX_KEYWORD_owned,
    OX_KEYWORD_textdomain
} OX_Keyword;
