static const OX_PunctNode
punct_nodes[] = {
    {0, 15, OX_TOKEN_END},
    {15, 2, OX_TOKEN_END},
    {17, 1, OX_TOKEN_lt_lt},
    {18, 2, OX_TOKEN_END},
    {20, 2, OX_TOKEN_gt_gt},
    {22, 1, OX_TOKEN_gt_gt_gt},
    {23, 2, OX_TOKEN_END},
    {25, 0, OX_TOKEN_eq_eq},
    {25, 1, OX_TOKEN_END},
    {26, 0, OX_TOKEN_bang_eq},
    {26, 0, OX_TOKEN_gt_eq},
    {26, 0, OX_TOKEN_lt_eq},
    {26, 2, OX_TOKEN_END},
    {28, 1, OX_TOKEN_star_star},
    {29, 2, OX_TOKEN_END},
    {31, 1, OX_TOKEN_pipe_pipe},
    {32, 2, OX_TOKEN_END},
    {34, 1, OX_TOKEN_amp_amp},
    {35, 1, OX_TOKEN_END},
    {36, 0, OX_TOKEN_plus_eq},
    {36, 1, OX_TOKEN_END},
    {37, 0, OX_TOKEN_minus_eq},
    {37, 0, OX_TOKEN_star_eq},
    {37, 0, OX_TOKEN_star_star_eq},
    {37, 1, OX_TOKEN_END},
    {38, 0, OX_TOKEN_slash_eq},
    {38, 1, OX_TOKEN_END},
    {39, 0, OX_TOKEN_percent_eq},
    {39, 0, OX_TOKEN_pipe_eq},
    {39, 0, OX_TOKEN_amp_eq},
    {39, 1, OX_TOKEN_END},
    {40, 0, OX_TOKEN_caret_eq},
    {40, 0, OX_TOKEN_lt_lt_eq},
    {40, 0, OX_TOKEN_gt_gt_eq},
    {40, 0, OX_TOKEN_gt_gt_gt_eq},
    {40, 0, OX_TOKEN_pipe_pipe_eq},
    {40, 0, OX_TOKEN_amp_amp_eq},
    {40, 1, OX_TOKEN_END},
    {41, 0, OX_TOKEN_tilde_eq},
    {41, 12, OX_TOKEN_END},
    {53, 1, OX_TOKEN_END},
    {54, 0, OX_TOKEN_dot_plus_eq},
    {54, 1, OX_TOKEN_END},
    {55, 0, OX_TOKEN_dot_minus_eq},
    {55, 2, OX_TOKEN_END},
    {57, 0, OX_TOKEN_dot_star_eq},
    {57, 1, OX_TOKEN_END},
    {58, 0, OX_TOKEN_dot_star_star_eq},
    {58, 1, OX_TOKEN_END},
    {59, 0, OX_TOKEN_dot_slash_eq},
    {59, 1, OX_TOKEN_END},
    {60, 0, OX_TOKEN_dot_percent_eq},
    {60, 2, OX_TOKEN_END},
    {62, 0, OX_TOKEN_dot_pipe_eq},
    {62, 2, OX_TOKEN_END},
    {64, 0, OX_TOKEN_dot_amp_eq},
    {64, 1, OX_TOKEN_END},
    {65, 0, OX_TOKEN_dot_caret_eq},
    {65, 1, OX_TOKEN_END},
    {66, 1, OX_TOKEN_END},
    {67, 0, OX_TOKEN_dot_lt_lt_eq},
    {67, 1, OX_TOKEN_END},
    {68, 2, OX_TOKEN_END},
    {70, 0, OX_TOKEN_dot_gt_gt_eq},
    {70, 1, OX_TOKEN_END},
    {71, 0, OX_TOKEN_dot_gt_gt_gt_eq},
    {71, 1, OX_TOKEN_END},
    {72, 0, OX_TOKEN_dot_pipe_pipe_eq},
    {72, 1, OX_TOKEN_END},
    {73, 0, OX_TOKEN_dot_amp_amp_eq},
    {73, 1, OX_TOKEN_END},
    {74, 0, OX_TOKEN_dot_tilde_eq},
    {74, 1, OX_TOKEN_END},
    {75, 0, OX_TOKEN_dot_dot_dot},
    {75, 0, OX_TOKEN_eq_gt},
    {75, 1, OX_TOKEN_END},
    {76, 0, OX_TOKEN_colon_gt}
};

static const OX_PunctEdge
punct_edges[] = {
    {'<', 1},
    {'>', 3},
    {'=', 6},
    {'!', 8},
    {'*', 12},
    {'|', 14},
    {'&', 16},
    {'+', 18},
    {'-', 20},
    {'/', 24},
    {'%', 26},
    {'^', 30},
    {'~', 37},
    {'.', 39},
    {':', 75},
    {'<', 2},
    {'=', 11},
    {'=', 32},
    {'>', 4},
    {'=', 10},
    {'>', 5},
    {'=', 33},
    {'=', 34},
    {'=', 7},
    {'>', 74},
    {'=', 9},
    {'*', 13},
    {'=', 22},
    {'=', 23},
    {'|', 15},
    {'=', 28},
    {'=', 35},
    {'&', 17},
    {'=', 29},
    {'=', 36},
    {'=', 19},
    {'=', 21},
    {'=', 25},
    {'=', 27},
    {'=', 31},
    {'=', 38},
    {'+', 40},
    {'-', 42},
    {'*', 44},
    {'/', 48},
    {'%', 50},
    {'|', 52},
    {'&', 54},
    {'^', 56},
    {'<', 58},
    {'>', 61},
    {'~', 70},
    {'.', 72},
    {'=', 41},
    {'=', 43},
    {'=', 45},
    {'*', 46},
    {'=', 47},
    {'=', 49},
    {'=', 51},
    {'=', 53},
    {'|', 66},
    {'=', 55},
    {'&', 68},
    {'=', 57},
    {'<', 59},
    {'=', 60},
    {'>', 62},
    {'=', 63},
    {'>', 64},
    {'=', 65},
    {'=', 67},
    {'=', 69},
    {'=', 71},
    {'.', 73},
    {'>', 76}
};

static const char*
puncts[] = {
    "<<",
    ">>",
    ">>>",
    "==",
    "!=",
    ">=",
    "<=",
    "**",
    "||",
    "&&",
    "+=",
    "-=",
    "*=",
    "**=",
    "/=",
    "%=",
    "|=",
    "&=",
    "^=",
    "<<=",
    ">>=",
    ">>>=",
    "||=",
    "&&=",
    "~=",
    ".+=",
    ".-=",
    ".*=",
    ".**=",
    "./=",
    ".%=",
    ".|=",
    ".&=",
    ".^=",
    ".<<=",
    ".>>=",
    ".>>>=",
    ".||=",
    ".&&=",
    ".~=",
    "...",
    "=>",
    ":>"
};
